name: unlearning_benchmark
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - pytorch-cuda=11.8
  - numpy
  - pandas
  - scikit-learn
  - pyyaml
  - pip
  - pip:
    - pytest
    - pytest-cov
    - black
    - ruff
